name: Deploy to GAE
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  deploy:
    name: Build and deploying to Google Cloud
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
    
    - id: commit
      uses: prompt/actions-commit-hash@v3
    
    - name: Build app
      run: go build -v

    - name: Login to gcloud
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: ${{ secrets.GCP_CREDENTIALS }}

    - name: Deploy to App Engine
      id: deploy
      uses: google-github-actions/deploy-appengine@v1
      with:
        deliverables: app.yaml
        version: v1
        project_id: ${{ secrets.GCP_PROJECT }}
        flags: |-
          --gcs-staging-source-dir=gs://us-artifacts-salaah-x/${{ github.workflow }}-${{ github.sha }}
        env_vars: |-
          VCS_REVISION=${{ steps.commit.outputs.short }}

    - name: Test
      run: curl "${{ steps.deploy.outputs.url }}"